name: server_demo
description: dart backend demo project
version: 0.0.1
publish_to: none

environment:
  sdk: ">3.0.1 <4.0.0"

dependencies:
  alfred: ^1.1.0+2
  corsac_jwt: ^1.0.0-nullsafety.1
  dbcrypt: ^2.0.0
  get_it: ^7.6.0
  mongo_dart: ^0.9.1
  

dev_dependencies:
  http: ^1.0.0
  test: ^1.24.3
